### ISSUE TITLE
BUG: prepare_cache is not concurrency safe

### ISSUE THREAD

**Issue by iwanb** [flakeheaven/flakeheaven#123]
I hit this when running flakeheaven with [pre-commit](https://pre-commit.com/) which runs multiple processes concurrently by default.

```
Traceback (most recent call last):
  File "venv/bin/flakeheaven", line 8, in <module>
    sys.exit(entrypoint())
  File "venv/lib/python3.9/site-packages/flakeheaven/_cli.py", line 40, in entrypoint
    exit_code, msg = main(argv)
  File "venv/lib/python3.9/site-packages/flakeheaven/_cli.py", line 32, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "venv/lib/python3.9/site-packages/flakeheaven/commands/_lint.py", line 12, in lint_command
    app.run(argv)
  File "venv/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "venv/lib/python3.9/site-packages/flake8/main/application.py", line 364, in _run
    self.run_checks()
  File "venv/lib/python3.9/site-packages/flake8/main/application.py", line 269, in run_checks
    self.file_checker_manager.start(files)
  File "venv/lib/python3.9/site-packages/flake8/checker.py", line 324, in start
    self.make_checkers(paths)
  File "venv/lib/python3.9/site-packages/flakeheaven/_patched/_checkers.py", line 63, in make_checkers
    prepare_cache()
  File "venv/lib/python3.9/site-packages/flakeheaven/_logic/_snapshot.py", line 20, in prepare_cache
    path.mkdir(parents=True)
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/root/.cache/flakeheaven'
```

The prepare_cache function can fail if multiple instances of flakeheaven run it a the same time. https://github.com/flakeheaven/flakeheaven/blob/d0f1254771272a3f950534dec512fba117fce545/flakeheaven/_logic/_snapshot.py#L18=

AFAIK it should be changed to something like this (`missing_ok` is Python >= 3.8):
```
def prepare_cache(path=CACHE_PATH):
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)
        return
    try:
      for fpath in path.iterdir():
          if time() - fpath.stat().st_atime <= THRESHOLD:
              continue
          fpath.unlink(missing_ok=True)  # Could be removed by another instance of flakeheaven
    except OSError:  # Ignore other issues like fpath not existing anymore
        pass
```

**Comment by pwoolvett** [comment]
Both changes do make sense, although the code would read funny... Have you tried runnig pre-commit with said modifications? I wonder if there's more of these. Anyway, PRs with proper testing are always welcome!

I believe pre-commit does have a require-serial or similar flag...
