### ISSUE TITLE
Flakeheaven fails with toml config

### ISSUE THREAD

**Issue by commentator8** [flakeheaven/flakeheaven#48]
I am trying to use flakeheaven to replace flakehell, and when I supply my pyproject.toml which has mypy overide sections (multiple sections with the same name) it fails to parse it.

```
configparser.DuplicateSectionError: While reading from 'service/pyproject.toml' [line 148]: section '[tool.mypy.overrides' already exists
```
The below is just an example.
```
[[tool.mypy.overrides]]
module = ["package1.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["package1.*"]
ignore_missing_imports = false
```

initially I had run it as follows (this is how my flakehell successfully runs)
```
/bin/bash -c 'cd service && flakeheaven lint ${@#*/} 2>/dev/null'
```

where the 2> is to silence logging errors flakehell had and the bash expansion is to remove the "service/" from the paths provided to it. This would work as it first changes dir to the directory where the toml is and flakehell picks it up automatically. But for some reason flakeheaven just silently passed with no output...

Anyway, the config seems to be an issue regardless and possible the cause of the second part.

Thanks!

**Comment by pwoolvett** [comment]
Why is configparser reading the configuration?

Could you show full trace and pip freeze?

**Comment by commentator8** [comment]
I was using flaheheaven lint --config /path/to/pyproject.toml

and the stacktrace was 

```
flakeheaven..............................................................Failed
- hook id: flakeheaven
- exit code: 1

Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/bin/flakeheaven", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flakeheaven/_cli.py", line 40, in entrypoint
    exit_code, msg = main(argv)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flakeheaven/_cli.py", line 32, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flakeheaven/commands/_lint.py", line 12, in lint_command
    app.run(argv)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flakeheaven/_patched/_app.py", line 162, in find_plugins
    local_plugins = get_local_plugins(config_finder)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/options/config.py", line 286, in get_local_plugins
    config = config_finder.cli_config(config_finder.config_file)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/options/config.py", line 83, in cli_config
    config, found_files = self._read_config(files)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-DEEVV_3n-py3.9/lib/python3.9/site-packages/flake8/options/config.py", line 66, in _read_config
    found_files.extend(config.read(filename))
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/configparser.py", line 1067, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from 'service/pyproject.toml' [line 148]: section '[tool.mypy.overrides' already exists
```

```
❯ pip freeze
acachecontrol==0.3.5
aiohttp==3.8.1
aiohttp-tus==1.0.0
aiosignal==1.2.0
alembic==1.7.5
anyio==3.5.0
argcomplete==1.12.3
asgiref==3.4.1
async-generator==1.10
async-timeout==4.0.2
asyncstdlib==3.10.2
attrs==21.2.0
beautifulsoup4==4.10.0
boto3==1.20.26
botocore==1.23.26
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.9
click==8.0.3
cryptography==36.0.1
decorator==5.1.1
distlib==0.3.4
ecdsa==0.17.0
fastapi==0.70.1
fastapi-versioning==0.10.0
filelock==3.4.2
frozendict==2.1.3
frozenlist==1.2.0
greenlet==1.1.2
h11==0.12.0
idna==3.3
iniconfig==1.1.1
jmespath==0.10.0
Mako==1.1.6
MarkupSafe==2.0.1
multidict==5.2.0
okta-jwt-verifier==0.2.3
outcome==1.1.0
packaging==21.3
platformdirs==2.4.1
pluggy==1.0.0
psycopg2-binary==2.9.2
py==1.11.0
pyasn1==0.4.8
pycparser==2.21
pydantic==1.8.2
PyJWT==2.3.0
pyOpenSSL==22.0.0
pyparsing==3.0.6
pytest==6.2.5
pytest-dotenv==0.5.2
python-dateutil==2.8.2
python-dotenv==0.18.0
python-jose==3.3.0
python-json-logger==2.0.2
PyYAML==6.0
requests==2.26.0
retry==0.9.2
rsa==4.8
s3transfer==0.5.0
selenium==4.1.0
sentry-sdk==1.5.1
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3.1
SQLAlchemy==1.4.29
starlette==0.16.0
toml==0.10.2
trio==0.19.0
trio-websocket==0.9.2
typing_extensions==4.0.1
urllib3==1.26.7
userpath==1.7.0
uvicorn==0.16.0
virtualenv==20.13.0
wsproto==1.0.0
yarl==1.7.2
```

**Comment by pwoolvett** [comment]
I am able to reproduce the issue. Seems flake8 changed its internal api which flahehell used to rely on...

**Comment by pwoolvett** [comment]
@commentator8 can you check if [PR](https://github.com/flakeheaven/flakeheaven/pull/49) ([branch](https://github.com/flakeheaven/flakeheaven/tree/fix/48)) solves your problem? tried it locally and it works for me...

**Comment by commentator8** [comment]
Thanks @pwoolvett. Strange issue, i'm installing it (first via poetry then directly via pip) and I am getting the following: 

```
❯ poetry update
Updating dependencies
Resolving dependencies... (24.0s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing flakeheaven (0.11.1 b6a51b2): Failed

  EnvCommandError

  Command ['/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/bin/pip', 'install', '--no-deps', '-U', '/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/src/flakeheaven'] errored with the following return code 2, and output:
  Looking in indexes: https://pypi.org/simple, https://user:****@git.****.com/api/v4/projects/89/packages/pypi/simple
  Processing /Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/src/flakeheaven
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Exception:
  Traceback (most recent call last):
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
      status = run_func(*args)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
      return func(self, options, args)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
      requirement_set = resolver.resolve(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
      collected = self.factory.collect_root_requirements(root_reqs)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
      req = self._make_requirement_from_install_req(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
      cand = self._make_candidate_from_link(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
      self._link_candidate_cache[link] = LinkCandidate(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
      super().__init__(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
      self.dist = self._prepare()
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
      dist = self._prepare_distribution()
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
      return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
      return self._prepare_linked_requirement(req, parallel_builds)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 556, in _prepare_linked_requirement
      dist = _get_prepared_distribution(
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
      abstract_dist.prepare_distribution_metadata(finder, build_isolation)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 45, in prepare_distribution_metadata
      self._install_build_reqs(finder)
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 104, in _install_build_reqs
      build_reqs = self._get_build_requires_wheel()
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 81, in _get_build_requires_wheel
      return backend.get_requires_for_build_wheel()
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
      return self._call_hook('get_requires_for_build_wheel', {
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
      raise BackendUnavailable(data.get('traceback', ''))
  pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
      obj = import_module(mod_path)
    File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "/private/var/folders/q8/04djpt6j51zgr4ryyj64n9640000gq/T/pip-build-env-b1vs9gfc/overlay/lib/python3.9/site-packages/poetry/core/masonry/__init__.py", line 10, in <module>
      from .builder import Builder
    File "/private/var/folders/q8/04djpt6j51zgr4ryyj64n9640000gq/T/pip-build-env-b1vs9gfc/overlay/lib/python3.9/site-packages/poetry/core/masonry/builder.py", line 7, in <module>
      from .builders.sdist import SdistBuilder
    File "/private/var/folders/q8/04djpt6j51zgr4ryyj64n9640000gq/T/pip-build-env-b1vs9gfc/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/__init__.py", line 2, in <module>
      from .wheel import WheelBuilder
    File "/private/var/folders/q8/04djpt6j51zgr4ryyj64n9640000gq/T/pip-build-env-b1vs9gfc/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 23, in <module>
      from packaging.tags import sys_tags
    File "/private/var/folders/q8/04djpt6j51zgr4ryyj64n9640000gq/T/pip-build-env-b1vs9gfc/overlay/lib/python3.9/site-packages/poetry/core/_vendor/packaging/tags.py", line 7, in <module>
      import distutils.util
    File "/Users/user/Library/Caches/pypoetry/virtualenvs/service-service-DEEVV_3n-py3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 92, in create_module
      return importlib.import_module('setuptools._distutils')
    File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ModuleNotFoundError: No module named 'setuptools'



  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│
      1185│         return decode(output)
      1186│
      1187│     def execute(self, bin, *args, **kwargs):
```

**Comment by commentator8** [comment]
Is this something on my end or yours? @pwoolvett

**Comment by pwoolvett** [comment]
> Is this something on my end or yours? @pwoolvett

can you try `pip install --upgrade pip setuptools wheel`, and then install flakeheaven from the fix/48 branch?

**Comment by commentator8** [comment]
Works like a charm. I'll be happy to take it and keep playing when it hits the main branch. Thanks!
