### ISSUE TITLE
ModuleNotFoundError: No module named 'flit_core.dummy'

### ISSUE THREAD

**Issue by uSpike** [flakeheaven/flakeheaven#64]
This started hitting our CI last night:
```
[INFO] Installing environment for https://github.com/flakeheaven/flakeheaven.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repo9roe07h2/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /root/.cache/pre-commit/repo9roe07h2
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [20 lines of output]
          Traceback (most recent call last):
            File "/root/.cache/pre-commit/repo9roe07h2/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
              main()
            File "/root/.cache/pre-commit/repo9roe07h2/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/root/.cache/pre-commit/repo9roe07h2/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line [164](https://gitlab.xes-mad.com/xes/sfweng/ats/ate/xtf/-/jobs/577834#L164), in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-ynn3u6ov/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
              metadata = make_metadata(module, ini_info)
            File "/tmp/pip-build-env-ynn3u6ov/overlay/lib/python3.10/site-packages/flit_core/common.py", line 399, in make_metadata
              md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
            File "/tmp/pip-build-env-ynn3u6ov/overlay/lib/python3.10/site-packages/flit_core/common.py", line 196, in get_info_from_module
              docstring, version = get_docstring_and_version_via_import(target)
            File "/tmp/pip-build-env-ynn3u6ov/overlay/lib/python3.10/site-packages/flit_core/common.py", line 171, in get_docstring_and_version_via_import
              spec.loader.exec_module(m)
            File "<frozen importlib._bootstrap_external>", line 883, in exec_module
            File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
            File "/root/.cache/pre-commit/repo9roe07h2/flakeheaven/__init__.py", line 5, in <module>
              from ._cli import entrypoint, flake8_entrypoint
          ModuleNotFoundError: No module named 'flit_core.dummy'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by uSpike** [comment]
This may be related to https://github.com/pypa/flit/issues/529

**Comment by uSpike** [comment]
Fixed in flit
